int _isupper(int c);
int _isdigit(int c);
int _isdigit(int c);
int _mul(int a, int b);
void print_numbers(void);
void print_most_numbers(void); 
void print_most_numbers(void); 
void more_numbers(void); 
void print_line(void); 
void print_diagonal(void); 
void print_square(void); 
void print_triangle(void);  
